package com.openfooddata.app.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BARCODE.
 */
public class Barcode {

    private Long id;
    private String barcode;
    private java.util.Date created_at;
    private java.util.Date updated_at;
    private Long product_id;

    public Barcode() {
    }

    public Barcode(Long id) {
        this.id = id;
    }

    public Barcode(Long id, String barcode, java.util.Date created_at, java.util.Date updated_at, Long product_id) {
        this.id = id;
        this.barcode = barcode;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.product_id = product_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBarcode() {
        return barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public java.util.Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(java.util.Date updated_at) {
        this.updated_at = updated_at;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

}
